package:
  name: hapog
  version: 1.3.3

source:
  url: https://github.com/institut-de-genomique/HAPO-G/archive/refs/tags/1.3.3.tar.gz
  sha256: "794339d326c7ddbfa215d2eb78c4eb2031049e675c5387caaa61d8ffe71a01b8"

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - 'htslib==1.11'
    - pip
  host:
    - 'python>=3.6'
    - 'htslib==1.11'
  run:
    - 'htslib==1.11'
    - 'python>=3.6'
    - 'biopython[channel=conda-forge]'
    - bwa
    - 'samtools==1.11'
    - minimap2

test:
  commands:
    - hapog -h

about:
  home: https://github.com/institut-de-genomique/HAPO-G
  license: OTHER
  license_file: LICENSE.md
  summary: Haplotype-Aware Polishing of Genomes
