package:
  name: hapog
  version: 1.3.2

source:
  url: https://github.com/institut-de-genomique/HAPO-G/archive/refs/tags/1.3.2.tar.gz
  sha256: "dbcf84dd4bb84323552c88437770192adadf833ad7a07bb7a12b4d60d034418f"

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - 'htslib==1.11'
  host:
    - 'python>=3.6'
    - 'htslib==1.11'
  run:
    - 'htslib==1.11'
    - 'python>=3.6'
    - 'biopython[channel=conda-forge]'
    - bwa
    - 'samtools==1.11'
    - minimap2

test:
  commands:
    - hapog -h

about:
  home: https://github.com/institut-de-genomique/HAPO-G
  license: OTHER
  license_file: LICENSE.md
  summary: Haplotype-Aware Polishing of Genomes
