package:
  name: hapog
  version: 1.3.2

source:
  url: https://github.com/institut-de-genomique/HAPO-G/archive/refs/tags/1.3.2.tar.gz
  sha256: "f0deabf0093344b2131383667e10b8130730a5484b5d7a3332f4c9187a9ba381"

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - htslib
  host:
    - 'python>=3.7'
    - htslib
  run:
    - htslib
    - 'python>=3.7'
    - 'biopython[channel=conda-forge]'
    - bwa
    - samtools
    - minimap2

test:
  commands:
    - hapog -h
    - hapog_bin -h

about:
  home: https://github.com/institut-de-genomique/HAPO-G
  license: OTHER
  license_file: LICENSE.md
  summary: Haplotype-Aware Polishing of Genomes
